### ISSUE TITLE
Not able to upload to CDN, Site usage goes up very high

### ISSUE THREAD

**Issue by mldunham** [Ipstenu/dreamspeed#18]
My install updated for the new release, everything seemed fine until I tried to upload more photos. The first 2 tries did not go to the CDN, the path showed them uploading locally instead. 
Usage on the site (I am on multisite) went up very high and I was not able to load the dashboard again until I renamed the plugin file. 

I don't know what is happening, but it appears there is an issue, perhaps with the new version and multisite? I'm guessing. I don't really know but it sounds logical. I checked the CDN and it is true, the photos are not being uploaded. There are no other paths on the CDN so it seems it just plain isn't saving to the CDN at all. Any ideas?

I want to go back to the last full release, but I don't seem to be able to find a full commit. What should I use? I would really like to get back to where I was so I can update my site.

**Comment by Ipstenu** [comment]
No reply in over a year. Can't reproduce :(
