### ISSUE TITLE
Copy files of specified file types to DreamSpeed as they are uploaded to the Media Library

### ISSUE THREAD

**Issue by redeemed2011** [Ipstenu/dreamspeed#19]
Howdy.

Thank you for putting this plugin together. :)

Does it seem plausible that others would benefit from adding a feature to this plugin that allows the user to enable auto-transferring certain file types uploaded to the media library? Ex: a user uploads a PDF and this plugin would upload it to the CDN and update refs to said PDF, whereas when the user uploads a JPEG nothing is moved to the CDN.

My use case (read if you desire) :
A site I am working on has need of moving audio, video, and documents to DreamObjects--we will not be using the CDN feature (aka, DreamSpeed) of DreamObjects. Though we must use DreamObjects for these file types, we do not want to sacrifice some nice features of our current hosting plan by moving all our images, css, js, etc. to DreamObjects. Thus, we have need of only uploading certain file types. Finally, this upload needs to be transparent to the user rather than giving them direct access to the DreamObjects buckets, teaching them additional steps to uploading to DreamObjects, teaching them how to figure out the new URL for the uploaded file(s), and relying on them to actually do this for every audio, video, or document file.

-sambo

**Comment by redeemed2011** [comment]
I'm working on adding this feature, and if it seems good to make public in your sight, then I'll create a pull request.

**Comment by Ipstenu** [comment]
That would be pretty cool for people who only want to use the CDN for PDFs. Please, pull away :D I would love that!

**Comment by redeemed2011** [comment]
Quick update. I got it written to filter audio, video & application (for PDFs) mime-types but don't have this feature added to the user options page, so it is always active at this time. Because I am limited on time each week it may take me a couple more weeks before I can get back to finishing this change.

**Comment by redeemed2011** [comment]
My site has been rather unstable and troubleshooting WP has been quite the challenge, therefore I am apprehensive of sharing my code changes thinking they may be contributing to the issue.
