### ISSUE TITLE
DreamObjects and DreamSpeed URLs

### ISSUE THREAD

**Issue by vikhiiz** [Ipstenu/dreamspeed#22]
Please help,
we have set up CDN following the instructions from DreamHosts site (see screenshot):
https://www.dropbox.com/s/dczbmfqbqx2g5a5/Screenshot%202016-09-13%2017.31.54.png?dl=0
We have done everything from the first step to the last.
However, our dreamobjects traffic is measured, but not dreamspeed cdn (take a look:)
https://www.dropbox.com/s/z2qg6y8omj0z7j7/Screenshot%202016-09-13%2017.33.25.png?dl=0
this is what we got from DH customer support:
https://www.dropbox.com/s/hqwq2jo65tnqpbt/Screenshot%202016-09-13%2017.34.26.png?dl=0

Can you please assist?
This is how our plugin is set up:
https://www.dropbox.com/s/o1ek6w8x2hz9ylc/Screenshot%202016-09-13%2017.35.15.png?dl=0

please help.
thanks.

**Comment by Ipstenu** [comment]
I do not provide support for the DreamObjects Panel pages. However if your site is showing images properly from dream.io then it's working, it's just not catching it as the dreamSpeed CDN part of the panel (which I didn't realize they'd changed...)

I can look into making the URL smarter, however I was told the plugin supposed to be pointing to the region and not the generic can URL. I'll have to follow up with them to see what they REALLY want.

**Comment by vikhiiz** [comment]
Thanks for your reply. Please do so (contact them). Hope we've provided all the information you need. 
have a great day,

bye
