### ISSUE TITLE
Re-upload/Scan Existing Media Option

### ISSUE THREAD

**Issue by Bullfrog117** [Ipstenu/dreamspeed#7]
First off, great job! I'm having a blast playing around with it. :-D

I've got all of my content transferred over (including unattached media), but I came across a feature that I would like: some kind of "re-upload/scan existing media" button (as a third option) that, instead of scanning for non-uploaded media, scans for media that has already been uploaded but was previously unattached and then updates posts and replaces existing links with CDN links to the uploaded media.

**Comment by Ipstenu** [comment]
After playing around with this, it's too 'expensive' from a computational angle. There's no easy way to detect what's done or not, and the force-overwrite via AWS was 'weird' and prone to failure.

Not at this time.
